version: '3.7'

services:
  # spring:
  #   build: ./backend/spring
  #   image: spring
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - spring:/data/spring
  #   depends_on: 
  #     - postgres
  #   networks: 
  #     - mefit

  # angular:
  #   container_name: angular
  #   build: ./frontend/angular
  #   ports:
  #     - '4200:80'

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mefit_db_dev
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - mefit
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - mefit
    restart: unless-stopped

networks:
  mefit:
    driver: bridge

volumes:
  # spring:
  postgres:
  pgadmin: